spring:
  security:
    user:
      name: jerry.hu
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/spring-demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root.123