server:
  port: 8081
  servlet:
    session:
      timeout: 120
    
spring:
  session:
    storeType: redis
    redis:
      flushMode: on-save
      namespace: spring:session
  redis:
    host: localhost
    port: 6379